"""create ExtractedExamData TopicImportance

Revision ID: 36bdeead1fe3
Revises: 620c69e83a85
Create Date: 2026-03-07 21:35:02.028546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36bdeead1fe3'
down_revision: Union[str, Sequence[str], None] = '620c69e83a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_importance',
    sa.Column('topic_name', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('total_marks_contribution', sa.Integer(), nullable=True),
    sa.Column('appearance_count', sa.Integer(), nullable=True),
    sa.Column('priority_level', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('topic_name')
    )
    op.create_index(op.f('ix_topic_importance_subject'), 'topic_importance', ['subject'], unique=False)
    op.create_index(op.f('ix_topic_importance_topic_name'), 'topic_importance', ['topic_name'], unique=False)
    op.create_table('extracted_exam_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['pyq_papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_exam_data_id'), 'extracted_exam_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_exam_data_id'), table_name='extracted_exam_data')
    op.drop_table('extracted_exam_data')
    op.drop_index(op.f('ix_topic_importance_topic_name'), table_name='topic_importance')
    op.drop_index(op.f('ix_topic_importance_subject'), table_name='topic_importance')
    op.drop_table('topic_importance')
    # ### end Alembic commands ###
