"""add_pyq_table

Revision ID: 620c69e83a85
Revises: 5af370925a55
Create Date: 2026-03-07 18:40:04.344663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '620c69e83a85'
down_revision: Union[str, Sequence[str], None] = '5af370925a55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pyq_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pyq_papers_id'), 'pyq_papers', ['id'], unique=False)
    op.create_index(op.f('ix_pyq_papers_subject'), 'pyq_papers', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pyq_papers_subject'), table_name='pyq_papers')
    op.drop_index(op.f('ix_pyq_papers_id'), table_name='pyq_papers')
    op.drop_table('pyq_papers')
    # ### end Alembic commands ###
